# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a99c90b70c8ffc24d5407aadd0c7dcad86db405a71ab5365bb3530f4a09fb4c3d8b89bb4d50d7f92d2ef5d41b7b3fb43417f33b64745da3c74858f8f07476cc

test:
  secret_key_base: 12a4c0029540e51180465f2ab415349775890906b971c9af2f50ef7fff08a88a2fb67aa66eef78470acaf8a9e49a50fffd348e7634e266266b271d65906ebbba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
